services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: address_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  mockoon:
    image: mockoon/cli:latest
    ports:
      - "3000:3000"
    volumes:
      - ./mocks:/data

volumes:
  mysql_data:
