spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:mysql://db:3306/address_db
    username: user
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver



cep:
  api:
    url: http://localhost:3000